apiVersion: v1
kind: Service
metadata:
  name: ms1-service
spec:
  selector:
    app: ms1
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 7000
    targetPort: 6000
    nodePort: 31401
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
      - name: ms1
        image: sagarlohani89/ms1:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
      imagePullSecrets:
      - name: regcred
